name: Publish

on: push

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: python3 setup.py sdist
    - run: python3 -m pip install --user --upgrade twine
    - run: python3 -m twine upload -p ${{ secrets.PYPI }} -u __token__ dist/*
